Demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Canteen/',include('Canteen.urls')),
    path('Stationary/',include('Stationary.urls')),
    path('Stream/',include('Stream.urls')),
    path('Student/',include('Student.urls')),
    path('UserManagement/',include('UserManagement.urls')),
    path('Library/',include('Library.urls')),
    path('Librarian/',include('Librarian.urls')),
    path('users/',include('users.urls')),
    path('rht/',include('rht.urls')),
    path('myadmin/',include('myadmin.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rht/urls.py
from django.conf.urls import url,include
from . import views


urlpatterns = [
url(r'^$',views.index_view),
]

users/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
url(r'^$',views.index_view),
#url(r'^role/', views.role),
url(r'^register/', views.register),
url(r'^signup/', views.registration1),
#url(r'^profile/', views.profile),
url(r'^login1/', views.login1),
url(r'^studentdetail/', views.studentdetail),

url(r'^mobilenumber/', views.mobilenumber),


#url(r'^role/', views.role),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Role(models.Model):
    Roleid=models.AutoField(primary_key=True)
    rolename=models.CharField(max_length=40)
    roleimg=models.ImageField(upload_to="users_media",blank=True,null=True)

class UserProfile(models.Model):
    id=models.AutoField(primary_key=True,default=0)
    userdata=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    DOB=models.DateField()
    Roleid=models.IntegerField(default=0)
    userimg=models.ImageField(upload_to="users_media",blank=True,null=True)
User.profile=property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

class MyUser(models.Model):
    user=models.CharField(max_length=30,unique=True)
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    email=models.EmailField(null=False,blank=False)
    uniqueid=models.IntegerField()
    phone_number = models.CharField(max_length=15,default="+910000000000")
    userimg=models.ImageField(upload_to="users_media",blank=True,null=True)

class Student(models.Model):
    STREAM_CHOICES = (
    ("Computer","COM_SCIENCE"),
    ("Chemical","CHEMICAL"),
    ("Mechanical","MECHANICAL"),
    ("Civil","CIVIL"),
)

    enroll=models.IntegerField(primary_key=True)
    user=models.CharField(max_length=30,unique=True)
    sem=models.IntegerField(null=False,blank=False)
    stream=models.CharField(max_length=30,choices=STREAM_CHOICES)
    balance=models.IntegerField(default=0)

class card(models.Model):
    enroll=models.IntegerField(primary_key=True)
    isblocked=models.BooleanField(default=False)

class Query(models.Model):
    queryid=models.AutoField(primary_key=True)
    querytext=models.CharField(null=False,blank=False,max_length=500,default="this is a query")
    date=models.DateTimeField(auto_now_add=True)
    isreviewed=models.BooleanField(default=False)

class mobile(models.Model):
    mobilenumber=models.CharField(max_length=15,default="+910000000000")
    otp=models.IntegerField(default=10)

    class Meta:
        get_latest_by='mobilenumber'

users/forms.py
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from users.models import UserProfile,MyUser,Student,mobile


class MyUserForm(forms.ModelForm):
    phone_number = forms.RegexField(regex=r'^((\+){1}91){1}[1-9]{1}[0-9]{9}$')
    #uniqueid=forms.IntegerField(uniqueid==111111111111 or uniqueid==222222222222 or uniqueid==333333333333 or uniqueid==444444444444)

    class Meta:
        model=MyUser
        fields="__all__"

class UserProfileForm(forms.ModelForm):
    DOB = forms.DateField(required=False, input_formats=['%Y-%m-%d','%m/%d/%Y','%m/%d/%y'] )
    class Meta:
        model=UserProfile
        fields=(
        'userdata',
        'Roleid',
        'DOB',
        'userimg'
        )

class StudentForm(forms.ModelForm):
    class Meta:
        model=Student
        exclude=('balance',)
class MobileForm(forms.ModelForm):
    mobilenumber = forms.RegexField(regex=r'^((\+){1}91){1}[1-9]{1}[0-9]{9}$')
    class Meta:
        model=mobile
        fields=('mobilenumber',)

users/views.py
from django.shortcuts import render,render_to_response,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import auth
import datetime
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from users.models import Role,UserProfile,MyUser,Student,card,mobile
from users.forms import MyUserForm,UserProfileForm,StudentForm,MobileForm
from django.contrib import messages
import requests
import random


def index_view(request):
    today = datetime.datetime.now().date()
    strwelcome="Welcome Admin and today is ",today
    return HttpResponse(strwelcome)
#____________________________________________________________________________________________________________________

#______________________________________________________________________________________________________________________--
def login1(request):
    if request.method == 'POST':

        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            print(username," --- ",raw_password)
            user = authenticate(username=username,password=raw_password)
            login(request,user)
            s=MyUser.objects.get(user=username)
            print('Hellobro')
            print(s.user)
            request.session['username']=s.user


            if s.uniqueid==111111111111:
                return HttpResponseRedirect('/Canteen/')
            if s.uniqueid==222222222222:
                return HttpResponseRedirect('/Stationary/')
            if s.uniqueid==333333333333:
                return HttpResponseRedirect('/Librarian/')
            if s.uniqueid==444444444444:
                return HttpResponseRedirect('/Student/index_view/')
            if s.uniqueid==555555555555:
                return HttpResponseRedirect('/myadmin/')
    else:

        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def register(request):
    if request.method=='POST':
        form=UserCreationForm(data=request.POST,files=request.FILES)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            print("here is the data")
            print(username)
            request.session['username']=username
            return HttpResponseRedirect('/users/signup/')
    else:
        form=UserCreationForm()
        context={'form':form}
        return render(request,'reg_form.html',context)



def registration1(request):
    context={}
    if request.method=='POST':
        form = MyUserForm(data=request.POST,files=request.FILES)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            uniqueid=form.cleaned_data.get('uniqueid')
            print(uniqueid)
            if uniqueid==444444444444:
                return HttpResponseRedirect('/users/studentdetail/')
            else:
                messages.success(request,"You've been successfully registered!!")
                return HttpResponseRedirect('/users/login1/')
        else:
            messages.error(request,"Submit the data as per requirement!!")
            username=request.session['username']
            form = MyUserForm()
            context['username']=username
            context['form']=form
            return render(request, 'reg_form1.html', context)

    else:
        username=request.session['username']
        print("this is session")
        print(username)
        form = MyUserForm()
        context['username']=username
        context['form']=form
    return render(request, 'reg_form1.html', context)

def studentdetail(request):
    context={}
    context={}
    if request.method=='POST':
        form = StudentForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            enrollment = form.cleaned_data.get('enroll')
            print("hey buddy ")
            print(enrollment)
            messages.success(request,"You've been successfully registered!!")
            s=card()
            s.enroll=enrollment
            s.isblocked=False
            s.save()
            return HttpResponseRedirect('/users/login1/')
    else:
        username=request.session['username']
        form=StudentForm()
        context['username']=username
        context['form']=form
    return render(request,"studentdetail.html",context)

def mobilenumber(request):
    context={}
    if request.method=='POST':
        print("this is post request")
        form = MobileForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            mobilenumber = form.cleaned_data.get('mobilenumber')
            request.session['mobilenumber']=mobilenumber
            if MyUser.objects.filter(phone_number=mobilenumber).exists():
                print("sending msg initiated")
                return sendsms(request)
            else:
                messages.warning(request,"enter valid mobile number")
                return HttpResponseRedirect('/users/mobilenumber/')
    else:
        form=MobileForm()
        context['form']=form
    return render(request,"mobilenumber.html",context)



def sendsms(request):
    otp=random.randint(111111,999999)
    print(otp)
    mobilenumber=request.session['mobilenumber']
    s=mobile.objects.latest()
    s.otp=otp
    s.save()
    mobilenumber1=str(mobilenumber)
    mn=mobilenumber1[3:]
    print(mn)

    url = "https://smsapi.engineeringtgr.com/send/"

    params = dict(
        Mobile='8264327271',
        Password='Iamrht362@',
        Key='rohity1TUrdf6wi2LA35FYo07m',
        Message=otp,
        To="8264327271")

    resp = requests.get(url, params)
    print(resp, resp.text)

users/templates/LoginAdmin.html
{% extends 'Battery/base.html' %}
{% load staticfiles %}
{% block content %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript">
        {% if key == '1' %}
            alert("Invalid Credentials");
        {% endif %}
    </script>
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'LoginPage/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'LoginPage/css/main.css' %}">
<!--===============================================================================================-->
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<!--<img src="{% static 'LoginPage/images/img-01.png' %}" alt="IMG">-->
                    <img src="{% static '011.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="post" action="{% url 'LoginAdmin' %}">
					{% csrf_token %}
                    <span class="login100-form-title">
						Admin Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="adminemail" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
				{% comment %}	<div class="container-login100-form-btn">
					<!--	<input type="submit" value="Login" class="login100-form-btn" name="LoginAdmin">

						</input>-->
                        <input type="submit" name="Ronnie" value="Login" class="login100-form-btn">
					</div>{% endcomment %}

                    <input type="submit" name="Ronnie" value="Login" class="login100-form-btn">

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'LoginPage/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginPage/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'LoginPage/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginPage/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'LoginPage/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'LoginPage/js/main.js' %}"></script>

</body>
{% endblock %}
</html>

users/templates/base9.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>| Hello | </title>
    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
   <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    <style>
      div.middle {
        position: relative;
        left: 260px;
        top:140px;

}
</style>

  </head>

  <body class="nav-md"  style=" background-image: linear-gradient(-90deg, #c5e4e5, white);">
    <div class="container body" background-img:url('/F:/project images/backgrounds/login.jpg')>
      <div class="main_container">




            <!-- sidebar menu -->

            <!-- /menu footer buttons -->

            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->

        <!-- /top navigation -->

        <!-- page content -->




{% block content %}

{% endblock %}

        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'build/js/custom.min.js' %}"></script>
  </body>
</html>

users/templates/login.html
<style>
  .container.login_section{position:relative;}
  .container.login_section:before{
    position:absolute;
    top:0;
    width:100%;
    height:100%;
    background:  rgba(0, 0, 0, 0.5);
  }
  .login_wrapper{margin-top:0 !important;}
  .login_content form {
    background: rgba(255, 255, 255, 0.2196078431372549);
    padding: 20px 15px;
}
.login_content form p, .login_content form .text_css{color: #fff; letter-spacing:1; text-shadow:none;}
input{
  background: transparent !important;
  box-shadow: none !important;
border: none !important;
border-bottom: 1px solid #fff !important;
height: 30px !important;
color: #fff !important;
}
::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
  color: #fff;
}

:-ms-input-placeholder { /* Internet Explorer 10-11 */
  color: #fff;
}

::-ms-input-placeholder { /* Microsoft Edge */
  color: #fff;
}
input.btn.btn-round.btn-default {
    border: 1px solid #fff !important;
    box-shadow: none;
    padding-top:4px !important;
}
.login_content h1:after, .login_content h1:before{display: none;}
</style>

{% extends 'base9.html' %}
{% block content %}
<div class="ui main container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}
</div>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div>
    <div class="container login_section" style="background: url(../../media/main_bg.png) no-repeat; height: 620px; background-size: cover;    background-position: right;">
<div class="login_wrapper">
  <div class="animate form login_form">
    <section class="login_content">
      <form method="post">
    <h1 style="color:white">Login</h1>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
    <input type="text" name="username" autofocus="" required="" id="id_username" placeholder="Enter Your Username" autocomplete="off">
   <input type="password" name="password" required="" id="id_password" placeholder="Enter Your Password" autocomplete="off">
    <button type="submit" class="btn btn-round btn-success">Sign in</button><br>
    <h6 class="text_css" style="color:white">Forget Password?</h6>
    <a href="/users/mobilenumber/"><input class="btn btn-round btn-default" type="button" value="Reset using mobile no"> </a>
    <div class="separator">
      <p class="change_link"><h6 class="text_css">New to site?</h6>
                  <a href="/users/register/" class="to_register"><input class="btn btn-round btn-default" type="button" value="Create Account"></a>
                </p>
                <div>
                    <!-- <h1 class="text-primary"><i class="fa fa-paw"></i> SAL Engineering &amp; Technical Institute</h1> -->

                  </div>
                  </div>
  </form>

  </section>
</div>
</div>
</div>
</div>

{% endblock %}

users/templates/profile.html
{% extends 'base9.html' %}

{% block content %}
  <h2>Profile</h2>
  <form method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
    <p><label for="id_userdata">Userdata:</label> <select name="userdata" required="" id="id_userdata">
  <option value="" selected="">---------</option>

  <option value="1">admin</option>

  <option value="27">nilay</option>

  <option value="28">bhuvan</option>

  <option value="29">Mihir</option>

</select></p>
<p><label for="id_Roleid">Roleid:</label> <input type="number" name="Roleid" value="0" required="" id="id_Roleid"></p>
<p><label for="id_DOB">Dob:</label> <input type="text" name="DOB" id="id_DOB"></p>
<p><label for="id_userimg">Userimg:</label> <input type="file" name="userimg" accept="image/*" id="id_userimg"></p>
    <button type="submit">Update</button>
  </form>
{% endblock %}

users/templates/reg_form1.html
<style>
  .container.body{
    background: url(../../media/main_bg.png) no-repeat; background-size: cover; background-position: right;
  }
  input{
    width:100%;
    margin-bottom:20px !important;
  }
  .login_content form {
    background: rgba(255, 255, 255, 0.2196078431372549);
    padding: 20px 15px;
}
.container.login_section:before {
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
}
ul{    padding-left: 15px;}
.login_content{padding-top:0;}
.login_wrapper{margin-top:0 !important;}
.login_content form {
  background: rgba(255, 255, 255, 0.2196078431372549);
  padding: 20px 15px;
}
form span, form ul li{color: #fff; text-shadow: none; font-style: italic; text-align:left;}
.login_content form p, .login_content form .text_css{color: #fff; letter-spacing:1; text-shadow:none;}
input{
background: transparent !important;
box-shadow: none !important;
border: none !important;
border-bottom: 1px solid #fff !important;
height: 30px !important;
color: #fff !important;
}
.login_content h2{text-shadow:none; color: #fff;}
::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
color: #fff;
}

:-ms-input-placeholder { /* Internet Explorer 10-11 */
color: #fff;
}

::-ms-input-placeholder { /* Microsoft Edge */
color: #fff;
}
input.btn.btn-round.btn-default {
  border: 1px solid #fff !important;
  box-shadow: none;
  padding-top:4px !important;
}
.login_content h1:after, .login_content h1:before{display: none;}
</style>
{% extends 'base9.html' %}


{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="ui {{message.extra_tags}} {{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div>


<div class="container login_section" style="background: url(../../media/main_bg.png) no-repeat; max-height:100%; height: 620px; background-size: cover;    background-position: right;">
<div class="login_wrapper">
    <div class="animate form login_form">
      <section class="login_content">

          <form method="post">
            <h2>Sign up</h2>
            <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
            <input type="hidden" name="user" value="{{username}}" maxlength="30" required="" id="id_user">
        <input type="text" placeholder="First name" name="first_name" maxlength="30" required="" id="id_first_name">
        <input type="text" placeholder="Last name" name="last_name" maxlength="30" required="" id="id_last_name">
        <input type="email" placeholder="Email" name="email" maxlength="254" required="" id="id_email">
        <input type="number" placeholder="Uniqueid provided by Admin" name="uniqueid" placeholder="provided by admin" required="" id="id_uniqueid">
        <input type="text" placeholder="Phone number" name="phone_number" placeholder="Format:+91xxxxxxxxxx" required="" id="id_phone_number">
        <input type="file" name="userimg" accept="image/*" id="id_userimg">
            <button type="submit" class="btn btn-round btn-success">Register</button>
          </form>


</section>
</div>
</div>
</div>
</div>

{% endblock %}

users/templates/studentdetail.html
<style>
  .container.body{
    background: url(../../media/main_bg.png) no-repeat; background-size: cover; background-position: right;
  }
  input{
    width:100%;
    margin-bottom:20px !important;
  }
  .login_content form {
    background: rgba(255, 255, 255, 0.2196078431372549);
    padding: 20px 15px;
}
.container.login_section:before {
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
}
ul{    padding-left: 15px;}
.login_content{padding-top:0;}
.login_wrapper{margin-top:0 !important;}
.login_content form {
  background: rgba(255, 255, 255, 0.2196078431372549);
  padding: 20px 15px;
}
form span, form ul li{color: #fff; text-shadow: none; font-style: italic; text-align:left;}
.login_content form p, .login_content form .text_css{color: #fff; letter-spacing:1; text-shadow:none;}
input{
background: transparent !important;
box-shadow: none !important;
border: none !important;
border-bottom: 1px solid #fff !important;
height: 30px !important;
color: #fff !important;
}
.login_content h2{text-shadow:none; color: #fff;}
::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
color: #fff;
}

:-ms-input-placeholder { /* Internet Explorer 10-11 */
color: #fff;
}

::-ms-input-placeholder { /* Microsoft Edge */
color: #fff;
}
input.btn.btn-round.btn-default {
  border: 1px solid #fff !important;
  box-shadow: none;
  padding-top:4px !important;
}
.login_content h1:after, .login_content h1:before{display: none;}
select{
  background: transparent;
    border: none;
    border-bottom: 1px solid #fff;
    width:100%;
    color: #fff !important;
}
select option{color: #000;}
</style>

{% extends 'base9.html' %}


{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="ui {{message.extra_tags}} {{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div>
  <div class="container login_section" style="background: url(../../media/main_bg.png) no-repeat; max-height:100%; height: 620px; background-size: cover;    background-position: right;">
  <div class="login_wrapper">
    <div class="animate form login_form">
      <section class="login_content">

  <form method="post">
<h2>Sign up</h2>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
    <input type="number" placeholder="Enroll" name="enroll" required="" id="id_enroll">
    <input type="hidden" name="user" value="{{username}}" maxlength="30" required="" id="id_user">
    <input type="number" placeholder="Sem" name="sem" required="" id="id_sem">
 <select name="stream" required="" id="id_stream">
  <option value="" selected="">Select Stream</option>

  <option value="Computer">COM_SCIENCE</option>

  <option value="Chemical">CHEMICAL</option>

  <option value="Mechanical">MECHANICAL</option>

  <option value="Civil">CIVIL</option>

</select>
    <button type="submit" class="btn btn-round btn-success">submit</button>
  </form>
</section>
</div>
</div>
</div>
</div>
{% endblock %}