Demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Canteen/',include('Canteen.urls')),
    path('Stationary/',include('Stationary.urls')),
    path('Stream/',include('Stream.urls')),
    path('Student/',include('Student.urls')),
    path('UserManagement/',include('UserManagement.urls')),
    path('Library/',include('Library.urls')),
    path('Librarian/',include('Librarian.urls')),
    path('users/',include('users.urls')),
    path('rht/',include('rht.urls')),
    path('myadmin/',include('myadmin.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Librarian/urls.py
from django.conf.urls import url,include
from . import views
from django.urls import path
from Librarian.views import *

urlpatterns = [
url(r'^$',views.index1,name="index1"),
url(r'logout/',views.logout1),
path('BookCategoryIndex1/',BookCategoryIndex1),
path('AddBookCategory1/',AddBookCategory1),
path('EditBookCategory1/',EditBookCategory1),
path('DeleteBookCategory1/',DeleteBookCategory1),
path('StreamForBookCat1/',StreamForBookCat1),
path('AddStream1/',AddStream1),
path('EditStream1/',EditStream1),
path('DeleteStream1/',DeleteStream1),
path('AddBook1/',AddBook1),
path('ShowBook1/',ShowBook1),
path('EditBook1/',EditBook1),
path('DeleteBook1/',DeleteBook1),
path('AddBookStock1/',AddBookStock1),
path('ShowStock1/',ShowStock1),
path('BookOrder1/',BookOrder1),
path('BookOrderStream1/',BookOrderStream1),
path('ShowBookForOrder1/',ShowBookForOrder1),
path('ShowStockForOrder1/',ShowStockForOrder1),
path('AddToCart1/',AddToCart1),
path('BookCart1/',BookCart2),
path('DeleteFromCart1/',DeleteFromCart1),
path('PlaceOrder3/',PlaceOrder3),
path('DetailOfOrder1/',DetailOfOrder1),
path('OrderShow4/',OrderShow4),
path('OrderShowById3/',OrderShowById3),
path('DetailOfOrderById3/',DetailOfOrderById3),
path('ReturnBook1/',ReturnBook1),
path('FineAmount/',FineAmount),
path('query/',putquery),
]

rht/urls.py
from django.conf.urls import url,include
from . import views


urlpatterns = [
url(r'^$',views.index_view),
]

Librarian/models.py
from django.db import models
from django.utils import timezone

class BookCategory1(models.Model):
    BookCatId=models.AutoField(primary_key=True)
    BookCatName=models.CharField(max_length=100)
    BookCategoryImg=models.ImageField(upload_to="Library_media",blank=True,null=True)

    def __str__(self):
        return self.BookCatName

class Stream1(models.Model):
    BookCatId=models.ForeignKey(BookCategory1,on_delete=models.CASCADE)
    StreamId=models.AutoField(primary_key=True)
    StreamName=models.CharField(max_length=100)
    class Meta:
        get_latest_by='StreamId'


class Book1(models.Model):
    BookCatId=models.ForeignKey(BookCategory1,on_delete=models.CASCADE)
    StreamId=models.ForeignKey(Stream1,on_delete=models.CASCADE)
    BookId=models.AutoField(primary_key=True)
    BookName=models.CharField(max_length=100,default="MYBOOK")
    Price=models.IntegerField(default=50)
    Edition=models.IntegerField(blank=True,null=True)
    CoverPageImg=models.ImageField(upload_to="Library_media",blank=True,null=True)
    BookSerialNumber=models.CharField(max_length=100,null=True,blank=True)
    PublishingYear=models.DateTimeField(auto_now_add=True)
    BookAuthorName=models.CharField(max_length=100,blank=True,default=True)

    class Meta:
        get_latest_by="BookId"

class BookStock1(models.Model):
    BookStockId=models.AutoField(primary_key=True)
    BookId=models.ForeignKey(Book1,on_delete=models.CASCADE)
    BookStockSerial=models.CharField(max_length=100)
    Issued=models.BooleanField(default=False)

class BookCart1(models.Model):
    #TempId=models.AutoField(primary_key=True)
    BookId=models.IntegerField(blank=True,null=True)
    BookName=models.CharField(max_length=100,default="MYBOOK")
    BookAuthorName=models.CharField(max_length=100,blank=True,default=True)
    BookSerialNumber=models.CharField(max_length=100,null=True,blank=True)
    BookStockSerial=models.CharField(max_length=100,default=1)
    Edition=models.IntegerField(blank=True,null=True)

class LibraryOrder1(models.Model):
    LibOrderId=models.AutoField(primary_key=True)
    UserId=models.IntegerField(default=True)
    DateOfOrder=models.DateField(auto_now_add=True)
    class Meta:
        get_latest_by='LibOrderId'

class LibOrderDetails1(models.Model):
    LODId=models.AutoField(primary_key=True)
    LibOrderId=models.ForeignKey(LibraryOrder1,on_delete=models.CASCADE)
    BookId=models.IntegerField(default=True)
    BookName=models.CharField(max_length=100,default="MYBOOK")
    BookSerialNumber=models.CharField(max_length=100,null=True,blank=True)
    BookStockSerial=models.CharField(max_length=100,default="01")
    IsReturned=models.BooleanField(default=False)

class ReturnBook(models.Model):
    ReturnId=models.AutoField(primary_key=True)
    BookStockSerial=models.CharField(max_length=100,default="01")
    DateOfOrder=models.DateField(blank=True)
    ReturnDate=models.DateField(auto_now_add=True)
    #Fine=models.IntegerField(null=True)

    class Meta:
        get_latest_by='ReturnId'

class FineAmount1(models.Model):
    FaId=models.AutoField(primary_key=True)
    User=models.IntegerField(default=True)
    DateOfFine=models.DateField(auto_now_add=True)
    FineAmount=models.IntegerField(default=0)

Librarian/forms.py
from django import forms
from Librarian.models import BookCategory1,Stream1,Book1,BookStock1,LibraryOrder1,ReturnBook,FineAmount1
from users.models import Query

class BookCategoryForm(forms.ModelForm):

    class Meta:
        model = BookCategory1
        fields = '__all__'

class StreamForm(forms.ModelForm):
    class Meta:
        model=Stream1
        fields='__all__'

class StreamEditForm(forms.ModelForm):
    class Meta:
        model=Stream1
        exclude=('BookCatId',)

class AddBookForm(forms.ModelForm):
    class Meta:
        model=Book1
        fields="__all__"

class EditBookForm(forms.ModelForm):
    class Meta:
        model=Book1
        exclude=('BookCatId','StreamId','BookId',)

class BookStockForm(forms.ModelForm):
    class Meta:
        model=BookStock1
        fields=("BookId","BookStockSerial","Issued",)

class LibOrderForm(forms.ModelForm):
    class Meta:
        model=LibraryOrder1
        fields="__all__"

class ReturnForm(forms.ModelForm):
    class Meta:
        model=ReturnBook
        fields="__all__"

class FineAmountForm(forms.ModelForm):
    class Meta:
        model=FineAmount1
        fields="__all__"
class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields="__all__"

Librarian/views.py
from django.shortcuts import render,HttpResponse
from django.http import HttpResponseRedirect
from django.template import loader
from Librarian.models import BookCategory1,Stream1,Book1,BookStock1,BookCart1,LibraryOrder1,LibOrderDetails1,ReturnBook,FineAmount1
from Librarian.forms import BookCategoryForm,StreamForm,StreamEditForm,AddBookForm,EditBookForm,BookStockForm,LibOrderForm,ReturnForm,FineAmountForm,QueryForm
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from users.views import MyUser
from django.contrib.auth import logout
from users.views import login1
from users.models import card,Student

@login_required
def logout1(request):
    logout(request)
    return login1(request)



@login_required
def index1(request):
    context={}
    username = request.session['username']
    context['username']=username
    s=MyUser.objects.get(user=username)
    context['data']=s
    return render(request,'Library_home1.html',context)
@login_required
def BookCategoryIndex1(request):
    context={}
    context['s']=BookCategory1.objects.all()
    return render(request,'BookCategoryIndex1.html',context)

@login_required
def AddBookCategory1(request):
    context = {}
    if request.method == 'GET':
        form = BookCategoryForm()
    elif request.method == "POST":
        form = BookCategoryForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            cat = form.save()
            return HttpResponseRedirect('/Librarian/BookCategoryIndex1/')
    context['form'] = form
    return render(request, 'AddBookCategory1.html', context)

@login_required
def EditBookCategory1(request):
    context = {}
    if request.method == 'GET' and 'BookCatId' in request.GET:
        BookCatId = request.GET['BookCatId']
        context['BookCatId'] = BookCatId
        instance = BookCategory1.objects.get(BookCatId=BookCatId)
        form = BookCategoryForm(instance=instance)

    elif request.method == "POST":
        BookCatId = request.GET['BookCatId']
        instance = BookCategory1.objects.get(BookCatId=BookCatId)
        form = BookCategoryForm(data=request.POST, instance=instance,files=request.FILES)
        if form.is_valid():
            pro = form.save()
            messages.success(request,"category %s is updated Sucessfully"%pro.BookCatName)
            return HttpResponseRedirect('/Librarian/BookCategoryIndex1/')
    else:
        return HttpResponse("category id is mandaory")
    context['form'] = form
    return render(request, 'AddBookCategory1.html', context)
@login_required
def DeleteBookCategory1(request):
    context = {}
    if request.method == 'GET' and 'BookCatId' in request.GET:
        BookCatId = request.GET['BookCatId']
        instance=BookCategory1.objects.get(BookCatId=BookCatId)
        context['BookCatId'] = instance
    elif request.method == "POST":
        BookCatId = request.GET['BookCatId']
        instance = BookCategory1.objects.get(BookCatId=BookCatId)
        messages.success(request, "Category <strong>%s</strong> is Deleted "%instance.BookCatName)
        instance.delete()
        return HttpResponseRedirect('/Librarian/BookCategoryIndex1')
    else:
        return HttpResponse("category id is mandaory")

    return render(request, 'DeleteBookCategory1.html', context)

@login_required
def StreamForBookCat1(request):
    context={ }

    BookCatId = request.GET['BookCatId']
    request.session['BookCatId']=BookCatId
    CatId1 = BookCategory1.objects.get(BookCatId=BookCatId)
    Cpro1  = CatId1.stream1_set.all()
    context={
        'CatId1':CatId1,
        'Cpro1':Cpro1,

    }
    return render(request,'StreamForBookCat1.html',context)

@login_required
def AddStream1(request):
    context={}
    if request.method=="GET":
        form=StreamForm()
    elif request.method=="POST":
        form=StreamForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            pro=form.save()
            messages.success(request,"New Stream is added succesfully")
            Latest=Stream1.objects.latest()
            got_cat_id=Latest.BookCatId_id
            return HttpResponseRedirect('/Librarian/StreamForBookCat1/?BookCatId='+str(got_cat_id))
    context['form']=form
    return render(request, 'AddStream1.html', context)
@login_required
def EditStream1(request):
    context = {}
    if request.method == 'GET' and 'StreamId' in request.GET:
        StreamId = request.GET['StreamId']
        context['StreamId'] = StreamId
        instance = Stream1.objects.get(StreamId=StreamId)
        form = StreamEditForm(instance=instance)

    elif request.method == "POST":
        StreamId = request.GET['StreamId']
        instance = Stream1.objects.get(StreamId=StreamId)
        temp=instance.BookCatId_id
        form = StreamEditForm(data=request.POST, instance=instance,files=request.FILES)
        if form.is_valid():
            pro = form.save()
            messages.success(request,"Stream '%s' is updated Sucessfully"%pro.StreamName)
            return HttpResponseRedirect('/Librarian/StreamForBookCat1/?BookCatId='+str(temp))
    else:
        return HttpResponse("Product id is mandaory")
    context['form'] = form
    return render(request, 'AddStream1.html', context)
@login_required
def DeleteStream1(request):
    context = {}
    if request.method == 'GET' and 'StreamId' in request.GET:
        StreamId = request.GET['StreamId']
        instance=Stream1.objects.get(StreamId=StreamId)
        context['StreamId'] = instance
    elif request.method == "POST":
        StreamId = request.GET['StreamId']
        instance = Stream1.objects.get(StreamId=StreamId)
        temp=instance.BookCatId_id
        messages.success(request, "Stream <strong>%s</strong> is Deleted "%instance.StreamName)
        instance.delete()
        return HttpResponseRedirect('/Librarian/StreamForBookCat1/?BookCatId='+str(temp))
    else:
        return HttpResponse("product id is mandaory")

    return render(request, 'DeleteStream1.html', context)
@login_required
def AddBook1(request):
    context={}
    if request.method=="GET":
        StreamId=request.GET['StreamId']
        BookCatId=request.session['BookCatId']
        BookCatIdName=BookCategory1.objects.get(BookCatId=BookCatId)
        print(BookCatIdName)
        StreamIdName=Stream1.objects.get(StreamId=StreamId)
        print(StreamIdName)
        template=loader.get_template('AddBook1.html')
        context={
        'StreamIdName':StreamId,
        'BookCatIdName':BookCatId,

        }

        form=AddBookForm()

    elif request.method=="POST":
        print("hello rht")
        form = AddBookForm(data=request.POST,files=request.FILES)
        if form.is_valid:
            pro=form.save()
            messages.success(request,"New Book is added succesfully")
            Latest=Book1.objects.latest()
            got_cat_id=Latest.BookCatId_id
            return HttpResponseRedirect('/Librarian/StreamForBookCat1/?BookCatId='+str(got_cat_id))
    context['form']=form
    return HttpResponse(template.render(context,request))
@login_required
def ShowBook1(request):
    context={}
    StreamId=request.GET['StreamId']
    BooksForStream=Book1.objects.filter(StreamId=StreamId)
    print(BooksForStream)
    context['BooksForStream']=BooksForStream
    return render(request,'ShowBook1.html',context)

@login_required
def EditBook1(request):
    context = {}
    if request.method == 'GET' and 'BookId' in request.GET:
        BookId = request.GET['BookId']
        context['BookId'] = BookId
        instance = Book1.objects.get(BookId=BookId)
        context['instance']=instance
        print(instance.BookName)
        form = EditBookForm(instance=instance)
    elif request.method == "POST":
        BookId = request.POST['BookId']
        instance = Book1.objects.get(BookId=BookId)
        form = EditBookForm(data=request.POST, instance=instance,files=request.FILES)
        if form.is_valid:
            pro = form.save()
            messages.success(request,"Book %s is updated Sucessfully"%pro.BookName)
            temp=instance.StreamId_id
            return HttpResponseRedirect('/Librarian/ShowBook1/?StreamId='+str(temp))
    else:
        return HttpResponse("Book id is mandaory")
    context['form'] = form
    return render(request, 'EditBook1.html', context)

@login_required
def DeleteBook1(request):
    context = {}
    if request.method == 'GET' and 'BookId' in request.GET:
        BookId = request.GET['BookId']
        instance=Book1.objects.get(BookId=BookId)
        context['BookId'] = instance
    elif request.method == "POST":
        BookId = request.GET['BookId']
        instance = Book1.objects.get(BookId=BookId)
        temp=instance.StreamId_id
        messages.success(request, "Book <strong>%s</strong> is Deleted "%instance.BookName)
        instance.delete()
        return HttpResponseRedirect('/Librarian/ShowBook1/?StreamId='+str(temp))
    else:
        return HttpResponse("Book id is mandaory")

    return render(request, 'DeleteBook1.html', context)
@login_required
def AddBookStock1(request):
    context={}
    if request.method=="GET" and "BookId" in request.GET:
        BookId=request.GET["BookId"]
        context["BookId"]=BookId
        #instance = Book.objects.get(BookId=BookId)
        form = BookStockForm()
    elif request.method == "POST":
        BookId = request.POST['BookId']
        instance = Book1.objects.get(BookId=BookId)
        form = BookStockForm(data=request.POST)
        if form.is_valid():
            pro = form.save()
            messages.success(request,"Book stock is updated Sucessfully")
            temp=instance.StreamId_id
            return HttpResponseRedirect('/Librarian/ShowBook1/?StreamId='+str(temp))
    else:
        return HttpResponse("Book id is mandaory")
    context['form'] = form
    return render(request, 'AddBookStock1.html', context)
@login_required

Librarian/templates/AddBook1.html
{% extends "base6.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}

  <form method="POST" enctype="multipart/form-data">
    {% if BookId %}
  <input type="hidden" value="{{BookId}}" name="BookId">
  {% endif %}



    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <table class="table">
  <tbody><tr><td><input type="hidden" name="BookCatId" value="{{BookCatIdName}}" required="" id="id_BookCatId">
    </td></tr>
  <tr><td><input type="hidden" name="StreamId" value="{{StreamIdName}}" required="" id="id_StreamId">
    </td></tr>
    <tr><th><label for="id_BookName">BookName:</label></th><td><input type="text" name="BookName" maxlength="100" required="" id="id_BookName"></td></tr>
    <tr><th><label for="id_Price">Price:</label></th><td><input type="number" name="Price" required="" id="id_Price"></td></tr>
    <tr><th><label for="id_Edition">Edition:</label></th><td><input type="number" name="Edition" id="id_Edition"></td></tr>
    <tr><th><label for="id_CoverPageImg">CoverPageImg:</label></th><td><input type="file" name="CoverPageImg" accept="image/*" id="id_CoverPageImg"></td></tr>
    <tr><th><label for="id_BookSerialNumber">BookSerialNumber:</label></th><td><input type="text" name="BookSerialNumber" maxlength="100" id="id_BookSerialNumber"></td></tr>

    <tr><th><label for="id_BookAuthorName">BookAuthorName/Publisher:</label></th><td><input type="text" name="BookAuthorName" maxlength="100" id="id_BookAuthorName"></td></tr>

    <tr>
    <td><a href="/Librarian/BookCategoryIndex1"><input class="btn btn-round btn-default" type="button" value="Back to categories"> </a></td>
    {% if BookId %}
    <td><input type="submit" value="Update" class="btn btn-round btn-primary"></td>
    {% else %}
    <td><input type="submit" value="Create" class="btn btn-round btn-primary"></td>
    {% endif %}
  </tr>

  </tbody></table>
  </form>

  </div>


{%endblock%}

Librarian/templates/AddBookStock1.html
{% extends "base6.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


  <form method="POST" enctype="multipart/form-data">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
    <table class="table">
  <tbody><tr><td><input type="hidden" name="BookId" value="{{BookId}}" required="" id="id_BookId">
    </td></tr>
  <tr><th><label for="id_BookStockSerial">BookStockSerial:</label></th><td><input type="text" name="BookStockSerial" maxlength="100" required="" id="id_BookStockSerial"></td></tr>
  <tr><th><label for="id_Issued">Issued:</label></th><td><input type="checkbox" name="Issued" id="id_Issued"></td></tr>
  <tr>
    <td><a href="/Librarian/BookCategoryIndex1/"><input class="btn btn-round btn-default" type="button" value="Back"> </a></td>

    <td><input type="submit" value="Update" class="btn btn-round btn-primary"></td>

  </tr>
  </tbody></table>
  </form>
  </div>


{%endblock%}

Librarian/templates/AddStream1.html
{% extends "base6.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


<form method="POST" enctype="multipart/form-data">
  {% if StreamId %}
  <input type="hidden" value="{{StreamId}}" name="StreamId">
  {% endif %}
  {% csrf_token %}
  <table class="table">
{{form.as_table}}
<tr>
  <td><a href="/Librarian/BookCategoryIndex1/"><input class="btn btn-round btn-default" type="button" value="Back"> </a></td>
  {% if StreamId %}
  <td><input type="submit" value="Update" class="btn btn-round btn-primary"></td>
  {% else %}
  <td><input type="submit" value="Create" class="btn btn-round btn-primary"></td>
  {% endif %}
</tr>
</table>
</form>
  </div>


{%endblock%}

Librarian/templates/BookOrder1.html
{% extends 'base6.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
<div class="x_content">
  <div class="right" style="position:relative;left:800px;">
  <a href="/Librarian/BookCart1/"><input class="btn btn-round btn-primary" type="button" value="Show cart"> </a>
  <!-- <a href="/Library/ClearCart"><input class="btn btn-round btn-primary" type="button" value="Clear Cart"> </a> -->
  </div>
  <div class="row">
  {% for book in book %}
  <div class="col-md-55" style="height:250px;width:250px;">
    <div class="thumbnail" style="height:240px;width:200px;background-image: linear-gradient(-65deg, #7a91a8, white);">
      <div class="image view view-first" style="height:150px;">

    <img src='../../media/{{book.BookCategoryImg}}' height='100%' width='100%'>
      </div>
    <div class="caption" style="background-image: linear-gradient(-65deg, #7a91a8, white);">
    <p><center><b>{{book.BookCatName}}</b></center>

    <center><a href="/Librarian/BookOrderStream1/?BookCatId={{book.BookCatId}}"><input class="btn btn-round btn-primary" type="button" value="Show"> </a></center>

    </p>
    </div>
    </div>
    </div>
  {% endfor %}

</div>
</div>

</div>


{% endblock %}

Librarian/templates/BookOrderStream1.html
{% extends 'base6.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}


<div class="container">
  <div class="x_content">
    <div class="row">
  {% for Stream in Stream %}

      <div class="caption" style="background-image: linear-gradient(-65deg, #7a91a8, white);">
      <p><center><b>{{Stream.StreamName}}</b></center>
        <center>
      <a href="/Librarian/ShowBookForOrder1/?StreamId={{Stream.StreamId}}"><input class="btn btn-round btn-primary" type="button" value="ShowBook"> </a>
      </center>
      </p>
      </div>

  {% endfor %}


</div>
</div>
</div>

{% endblock %}

Librarian/templates/DeleteBookCategory1.html
{% extends "base6.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
<h3>Are you sure you want to delete Category
      '{{BookCatId.BookCatName}}'
      ?
</h3>
<form method="POST">
    {% csrf_token %}
    <a href="/Librarian/BookCategoryIndex1"><input class="btn btn-round btn-default" type="button" value="Cancel"> </a>
    <input type="submit" value="Delete" class="btn btn-round btn-danger">
</form>
</div>

{%endblock%}

Librarian/templates/DeleteStream1.html
{% extends "base6.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
<h3>Are you sure you want to delete Stream
    '{{StreamId.StreamName}}'
    ?
</h3>
<form method="POST">
  {% csrf_token %}
  <a href="/Librarian/BookCategoryIndex1"><input class="btn btn-round btn-default" type="button" value="Cancel"> </a>
  <input type="submit" value="Delete" class="btn btn-round btn-danger">
</form>
</div>

{%endblock%}

Librarian/templates/DetailOfOrderById4.html
{% extends 'base6.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <table class="table">
    <tr><th><b>Book Id</b></th><th><b>Book Name</b></th><th><b>Serial Number</b></th><th><b>Stock Number<b></th></tr>
    <tr><th></th><th></th><th></th><th></th></tr>
  {% for c1 in data %}
  <tr>
    <td><b> {{c1.BookId}}</b></td>
    <td><b> {{c1.BookName}}</b></td>
    <td><b> {{c1.BookSerialNumber}}</b></td>
    <td><b>{{c1.BookStockSerial}}</b></td>

    {% if c1.IsReturned %}
    <td><b>Returned</b></td>
    {% else %}
    <td><a href="/Librarian/ReturnBook1/?BookStockSerial={{c1.BookStockSerial}}"><input class="btn btn-round btn-primary" type="button" value="Return"></a></td>
    {% endif %}
  </tr>

  {% endfor %}
    </table>
    <a href="/Librarian/OrderShow4/"><input class="btn btn-round btn-default" type="button" value="back to history"> </a>
</div>


{% endblock %}

Librarian/templates/FineAmount.html
{% extends "base6.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


<form method="POST" enctype="multipart/form-data">

  {% csrf_token %}
  <table class="table">
{{form.as_table}}
<tr>



  <td><input type="submit" value="Pay and Return" class="btn btn-round btn-primary"></td>


</tr>
</table>
</form>
  </div>


{%endblock%}

Librarian/templates/thanks3.html
{% extends "base6.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}

<h1>Thanks for the Order</h1>
  </div>
<a href="/Librarian/BookOrder1"><input class="btn btn-round btn-default" type="button" value="Back to categories"> </a>

{%endblock%}