Demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Canteen/',include('Canteen.urls')),
    path('Stationary/',include('Stationary.urls')),
    path('Stream/',include('Stream.urls')),
    path('Student/',include('Student.urls')),
    path('UserManagement/',include('UserManagement.urls')),
    path('Library/',include('Library.urls')),
    path('Librarian/',include('Librarian.urls')),
    path('users/',include('users.urls')),
    path('rht/',include('rht.urls')),
    path('myadmin/',include('myadmin.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Stationary/urls.py
from django.conf.urls import url,include
from . import views
from django.urls import path
from Stationary.views import *

urlpatterns = [
url(r'^$',views.index,name="index"),
url(r'logout',views.logout1),
path('Scategory_index/',Scategory_index),
path('add_Scategory/', create_Scategory),
path('edit_Scategory/',edit_Scategory),
path('delete_Scategory/',delete_Scategory),

path('Sproduct_index/',Sproduct_index),
path('add_Sproduct/', create_Sproduct),
path('edit_Sproduct/',edit_Sproduct),
path('delete_Sproduct/',delete_Sproduct),
path('SproductbyId/',SproductbyId),
path('Scategory_order/',Scategory_order),
path('Scategory_order_productbyId/',Scategory_order_productbyid),
path('Scategory_order_productbyId/productdetail/',productdetail),
path('StationaryCart/',CartShow),
path('ClearCart/',ClearCart),
path('EditFromCart1/',EditFromCart),
path('DeleteFromCart1/',DeleteFromCart),
path('PlaceOrder1/',PlaceOrder),
path('DetailOfOrder1/',DetailOfOrder1),
path('OrderShow1/',OrderShow1),
path('OrderShowById1/',OrderShowById1),
path('DetailOfOrderById1/',DetailOfOrderById1),
path('query/',putquery),



]

rht/urls.py
from django.conf.urls import url,include
from . import views


urlpatterns = [
url(r'^$',views.index_view),
]

Stationary/models.py
from django.db import models

class Scategory(models.Model):
    CatId=models.AutoField(primary_key=True)
    CatName=models.CharField(max_length=100)
    CatImg=models.ImageField(upload_to="Scategory_media",blank=True,null=True)
    def __str__(self):
        return self.CatName



class Sproduct(models.Model):
    CatId=models.ForeignKey(Scategory,on_delete=models.CASCADE)
    Pid=models.AutoField(primary_key=True)
    PName=models.CharField(max_length=100)
    Price=models.IntegerField()
    PImg=models.ImageField(upload_to="Sproduct_media",blank=True,null=True)
    IsAvailable=models.BooleanField(default=True)
    def __str__(self):
        return self.PName
    class Meta:
        get_latest_by='Pid'

class CartProduct(models.Model):
    #TempId=models.AutoField(primary_key=True)
    Pid=models.ForeignKey(Sproduct,on_delete=models.CASCADE)
    Price=models.IntegerField(default=50)
    quantity=models.IntegerField(null=False)
    class Meta:
        get_latest_by='Pid'


class StatOrder(models.Model):
    StatOrderId=models.AutoField(primary_key=True)
    UserId=models.IntegerField(default=True)
    DateOfOrder=models.DateTimeField(auto_now_add=True)
    class Meta:
        get_latest_by='StatOrderId'

class StatOrderDetails(models.Model):
    SODId=models.AutoField(primary_key=True)
    StatOrderId=models.ForeignKey(StatOrder,on_delete=models.CASCADE)
    Pid=models.ForeignKey(Sproduct,on_delete=models.CASCADE)
    Price=models.IntegerField(default=True)
    quantity=models.IntegerField(null=False)

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Role(models.Model):
    Roleid=models.AutoField(primary_key=True)
    rolename=models.CharField(max_length=40)
    roleimg=models.ImageField(upload_to="users_media",blank=True,null=True)

class UserProfile(models.Model):
    id=models.AutoField(primary_key=True,default=0)
    userdata=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    DOB=models.DateField()
    Roleid=models.IntegerField(default=0)
    userimg=models.ImageField(upload_to="users_media",blank=True,null=True)
User.profile=property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

class MyUser(models.Model):
    user=models.CharField(max_length=30,unique=True)
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    email=models.EmailField(null=False,blank=False)
    uniqueid=models.IntegerField()
    phone_number = models.CharField(max_length=15,default="+910000000000")
    userimg=models.ImageField(upload_to="users_media",blank=True,null=True)

class Student(models.Model):
    STREAM_CHOICES = (
    ("Computer","COM_SCIENCE"),
    ("Chemical","CHEMICAL"),
    ("Mechanical","MECHANICAL"),
    ("Civil","CIVIL"),
)

    enroll=models.IntegerField(primary_key=True)
    user=models.CharField(max_length=30,unique=True)
    sem=models.IntegerField(null=False,blank=False)
    stream=models.CharField(max_length=30,choices=STREAM_CHOICES)
    balance=models.IntegerField(default=0)

class card(models.Model):
    enroll=models.IntegerField(primary_key=True)
    isblocked=models.BooleanField(default=False)

class Query(models.Model):
    queryid=models.AutoField(primary_key=True)
    querytext=models.CharField(null=False,blank=False,max_length=500,default="this is a query")
    date=models.DateTimeField(auto_now_add=True)
    isreviewed=models.BooleanField(default=False)

class mobile(models.Model):
    mobilenumber=models.CharField(max_length=15,default="+910000000000")
    otp=models.IntegerField(default=10)

    class Meta:
        get_latest_by='mobilenumber'

Stationary/forms.py
from django import forms
from Stationary.models import Scategory,Sproduct,CartProduct,StatOrder
from users.models import Query

class ScategoryForm(forms.ModelForm):

    class Meta:
        model = Scategory
        fields = '__all__'
class SproductForm(forms.ModelForm):


    class Meta:
        model = Sproduct
        fields='__all__'

class ScategoryDelete(forms.ModelForm):
    class Meta:
        model = Scategory
        fields=('CatName',)

class SproductDelete(forms.ModelForm):
    class Meta:
        model=Sproduct
        fields=('PName',)

class SproductEdit(forms.ModelForm):
    class Meta:
        model=Sproduct
        exclude=('CatId',)

class CartProductForm(forms.ModelForm):
     class Meta:
         model = CartProduct
         exclude=('aggregate',)
class SOrderForm(forms.ModelForm):
     class Meta:
         model = StatOrder
         fields='__all__'
class EditCartProduct1(forms.ModelForm):
    class Meta:
        model = CartProduct
        fields=('quantity',)

class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields="__all__"

Stationary/views.py
from django.shortcuts import render,HttpResponse
from django.http import HttpResponseRedirect
from django.template import loader
from Stationary.models import Scategory, Sproduct,CartProduct,StatOrder,StatOrderDetails
from django.contrib import messages
from users.models import MyUser,card,Student
from django.contrib.auth.decorators import login_required
from Stationary.forms import ScategoryForm,SproductForm,ScategoryDelete,SproductDelete,SproductEdit,CartProductForm,SOrderForm,EditCartProduct1,QueryForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login ,logout
from users.views import login1

@login_required
def logout1(request):
    logout(request)
    return login1(request)

@login_required
def index(request):
    context={}
    username = request.session['username']
    context['username']=username
    s=MyUser.objects.get(user=username)
    context['data']=s
    return render(request,'Scategory_home.html',context)

@login_required
def Scategory_index(request):
    context={}
    context['cat']=Scategory.objects.all()
    return render(request,'Scategory_index.html',context)
@login_required
def create_Scategory(request):
    context = {}
    if request.method == 'GET':
        form = ScategoryForm()
    elif request.method == "POST":
        form = ScategoryForm(data=request.POST)
        if form.is_valid():
            cat = form.save()
            messages.success(request, " New Category Added ")
            return HttpResponseRedirect('/Stationary/Scategory_index/')

    context['form'] = form
    return render(request, 'Scategory_create.html', context)

@login_required
def edit_Scategory(request):
    context = {}
    if request.method == 'GET' and 'CatId' in request.GET:
        CatId = request.GET['CatId']
        context['CatId'] = CatId
        instance = Scategory.objects.get(CatId=CatId)
        form = ScategoryForm(instance=instance)

    elif request.method == "POST":
        CatId = request.POST['CatId']
        instance = Scategory.objects.get(CatId=CatId)
        form = ScategoryForm(data=request.POST, instance=instance,files=request.FILES)
        if form.is_valid():
            pro = form.save()
            messages.success(request,"category %s is updated Sucessfully"%pro.CatName)
            return HttpResponseRedirect('/Stationary/Scategory_index/')
    else:
        return HttpResponse("category id is mandaory")
    context['form'] = form
    return render(request, 'Scategory_create.html', context)
@login_required
def EditFromCart(request):
    context={}
    if request.method=='GET' and 'Pid' in request.GET:
        Pid = request.GET['Pid']
        context['Pid']=Pid
        instance=CartProduct.objects.get(Pid=Pid)
        form=EditCartProduct1(instance=instance)
    elif request.method=="POST":
        Pid=request.POST['Pid']
        instance=CartProduct.objects.get(Pid=Pid)
        form=EditCartProduct1(data=request.POST,instance=instance)
        if form.is_valid():
            pro=form.save()
            messages.success(request,"cart updated successfully")
            return HttpResponseRedirect("/Stationary/StationaryCart/")
    else:
        return HttpResponse("product id is mandatory")
    context["form"]=form
    return render(request,"EditFromCart1.html",context)


@login_required
def delete_Scategory(request):
    context = {}
    if request.method == 'GET' and 'CatId' in request.GET:
        CatId = request.GET['CatId']
        instance=Scategory.objects.get(CatId=CatId)
        context['CatId'] = instance
    elif request.method == "POST":
        CatId = request.GET['CatId']
        instance = Scategory.objects.get(CatId=CatId)
        messages.success(request, "Category <strong>%s</strong> is Deleted "%instance.CatName)
        instance.delete()
        return HttpResponseRedirect('/Stationary/Scategory_index')
    else:
        return HttpResponse("category id is mandaory")

    return render(request, 'Scategory_delete.html', context)

@login_required
def Scategory_order(request):
    context={}
    context['cat']=Scategory.objects.all()
    return render(request,'Scategory_order.html',context)

@login_required
def Sproduct_index(request):
    context={}
    context['pro']=Sproduct.objects.all()
    return render(request,"Sproduct_index.html",context)

@login_required
def edit_Sproduct(request):
    context = {}
    if request.method == 'GET' and 'Pid' in request.GET:
        Pid = request.GET['Pid']
        context['Pid'] = Pid
        instance = Sproduct.objects.get(Pid=Pid)
        form = SproductEdit(instance=instance)

    elif request.method == "POST":
        Pid = request.POST['Pid']
        instance = Sproduct.objects.get(Pid=Pid)
        temp=instance.CatId_id
        form = SproductEdit(data=request.POST, instance=instance,files=request.FILES)
        if form.is_valid():
            pro = form.save()
            messages.success(request,"Product '%s' is updated Sucessfully"%pro.PName)
            return HttpResponseRedirect('/Stationary/SproductbyId/?CatId='+str(temp))
    else:
        return HttpResponse("Product id is mandaory")
    context['form'] = form
    return render(request, 'Sproduct_create.html', context)
@login_required
def create_Sproduct(request):
    context = {}
    if request.method == 'GET':
        form = SproductForm()
    elif request.method == "POST":
        form = SproductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            pro = form.save()
            messages.success(request,'new product is added successfully')
            Latest=Sproduct.objects.latest()
            got_cat_id=Latest.CatId_id
            return HttpResponseRedirect('/Stationary/SproductbyId/?CatId='+str(got_cat_id))
    context['form']=form
    return render(request, 'Sproduct_create.html', context)

@login_required
def delete_Sproduct(request):
    context = {}
    if request.method == 'GET' and 'Pid' in request.GET:
        Pid = request.GET['Pid']
        instance=Sproduct.objects.get(Pid=Pid)
        context['Pid'] = instance
    elif request.method == "POST":
        Pid = request.GET['Pid']
        instance = Sproduct.objects.get(Pid=Pid)
        temp=instance.CatId_id
        messages.success(request, "product <strong>%s</strong> is Deleted "%instance.PName)
        instance.delete()
        return HttpResponseRedirect('/Stationary/SproductbyId/?CatId='+str(temp))
    else:
        return HttpResponse("product id is mandaory")

    return render(request, 'Sproduct_delete.html', context)

@login_required
def SproductbyId(request):
    context={ }
    CatId = request.GET['CatId']
    CatId1 = Scategory.objects.get(CatId=CatId)
    Cpro1  = CatId1.sproduct_set.all()
    context={
        'CatId1':CatId1,
        'Cpro1':Cpro1,

    }
    return render(request,'SproductbyId.html',context)

@login_required
def Scategory_order_productbyid(request):
    context={ }
    CatId = request.GET['CatId']
    CatId1 = Scategory.objects.get(CatId=CatId)
    Cpro1  = CatId1.sproduct_set.all()
    context={
        'CatId1':CatId1,
        'Cpro1':Cpro1,

    }
    return render(request,'Scategory_order_productbyid.html',context)

@login_required
def OrderDetails(request):
    context = {}
    if request.method == 'GET':
        form = OrderDetailsForm()
    elif request.method == "POST":
        form = OrderDetailsForm(data=request.POST)
        if form.is_valid():
            order = form.save()

            return HttpResponseRedirect('/Stationary/Scategory_index/')
    context['form'] = form
    return render(request, 'Sorder_details.html', context)

@login_required
def CartShow(request):
    context={}
    context['cat']=CartProduct.objects.all()
    s1=CartProduct.objects.all()
    mul=1
    add=0
    for i in s1:
        mul=i.Price*i.quantity
        add=add+mul
        request.session['add']=add
    context['add']=add
    return render(request,'StationaryCart.html',context)

@login_required
def ClearCart(request):
    instance=CartProduct.objects.all()
    instance.delete()
    messages.success(request,"cart is empty now.You can add new products")
    return HttpResponseRedirect('/Stationary/Scategory_order')

@login_required
def productdetail(request):
    if request.method == "GET":
        Pid = request.GET['Pid']
        pro=Sproduct.objects.filter(Pid=Pid)
        #set_views_count("product", request, pro[0])
        template=loader.get_template('productdetail1.html')
        context={
            'pro':pro[0]
        }
        form = CartProductForm()
    elif request.method == "POST":
        form=CartProductForm(data=request.POST)

        if form.is_valid():
            pro=form.save()

            Pid = form.cleaned_data.get('Pid')
            s=CartProduct.objects.filter(Pid=Pid)
            print("hi canteen")
            print(s)
            count=0
            for i in s:
                count=count+1
            print(count)
            if count>1:
                messages.warning(request,"product is already added in the cart.You can add/remove quantity from cart")
                s=CartProduct.objects.latest()
                s.delete()
                return HttpResponseRedirect('/Stationary/StationaryCart/')
            else:
                messages.success(request,' product is added successfully to cart')
                return HttpResponseRedirect('/Stationary/Scategory_order/')
    context['form'] = form
    return HttpResponse(template.render(context,request))

@login_required
def DeleteFromCart(request):
    Pid = request.GET['Pid']
    instance = CartProduct.objects.get(Pid=Pid)
    messages.success(request, "product is deleted from cart")
    instance.delete()
    return HttpResponseRedirect('/Stationary/StationaryCart/')

@login_required
def PlaceOrder(request):
    context={}
    if request.method == "GET":
        #Pid = request.GET['Pid']
        #pro=Cproduct.objects.filter(Pid=Pid)
        #set_views_count("product", request, pro[0])

Stationary/templates/DetailOfOrderById1.html
{% extends 'base1.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <table class="table">
    <tr><th><b>Product Name</b></th><th><b>Price</b></th><th><b>Quantity</b></th><th><b>Total<b></th>
    <tr><th></th><th></th><th></th></tr>
  {% for c1 in data %}
  <tr>
    <td><b> {{c1.Pid}}</b></td>
    <td><b> {{c1.Price}}</b></td>
    <td><b> {{c1.quantity}}</b></td>
    <td><b>{% widthratio c1.Price 1 c1.quantity %}</b></td>
  </tr>

  {% endfor %}
    </table>
    <div style="position: relative;
left: 722px;">
    <b>Total amount to be paid:</b> <b>{{add}}</b>
    </div>
<a href="/Stationary/OrderShow1/"><input class="btn btn-round btn-default" type="button" value="Back to history"> </a>
</div>


{% endblock %}

Stationary/templates/EditFromCart1.html
{% extends "base1.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


<form method="POST" enctype="multipart/form-data">
  {% if Pid %}
  <input type="hidden" value="{{Pid}}" name="Pid">
  {% endif %}
  {% csrf_token %}
  <table class="table">
{{form.as_table}}
<tr>
  <td><a href="/Stationary/StationaryCart/"><input class="btn btn-round btn-default" type="button" value="Back"> </a></td>

  <td><input type="submit" value="Update" class="btn btn-round btn-primary"></td>
</tr>
</table>
</form>
  </div>


{%endblock%}

Stationary/templates/OrderShow1.html
{% extends 'base1.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <form method="POST" action="">
      {% csrf_token %}

  <b>Search by Id</b><input type="text" name="StudentNumber" value="">
  <input class="btn btn-round btn-primary" type="submit" value="Show">
  </form>
  <table class="table">

      <tr><td><b>StudentId<b></td><td><b>DateTime</b></td></tr>
  {% for c1 in instance %}
  <tr>
    
    <td><b> {{c1.UserId}}</b></td>
    <td><b> {{c1.DateOfOrder}}</b></td>
    <td><a href="/Stationary/DetailOfOrderById1/?StatOrderId={{c1.StatOrderId}}"><input class="btn btn-round btn-primary" type="button" value="Detail"> </a></td>

  </tr>

  {% endfor %}
    </table>
  <div>


{% endblock %}

Stationary/templates/OrderShowById1.html
{% extends 'base1.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">

  <table class="table">

      <tr><td><b>StudentId<b></td><td><b>DateTime</b></td></tr>
  {% for c1 in s1 %}
  <tr>
    
    <td><b> {{c1.UserId}}</b></td>
    <td><b> {{c1.DateOfOrder}}</b></td>
    <td><a href="/Stationary/DetailOfOrderById1/?StatOrderId={{c1.StatOrderId}}"><input class="btn btn-round btn-primary" type="button" value="Detail"> </a></td>

  </tr>

  {% endfor %}
    </table>
    <a href="/Stationary/OrderShow1/"><input class="btn btn-round btn-default" type="button" value="Back to history"> </a>
  <div>


{% endblock %}

Stationary/templates/Scategory_delete.html
{% extends "base1.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
<h3>Are you sure you want to delete Category
      '{{CatId.CatName}}'
      ?
</h3>
<form method="POST">
    {% csrf_token %}
    <a href="/Stationary/Scategory_index"><input class="btn btn-round btn-default" type="button" value="Cancel"> </a>
    <input type="submit" value="Delete" class="btn btn-round btn-primary">
</form>
</div>

{%endblock%}

Stationary/templates/Scategory_home.html
{% extends "base1.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
  <h3><marquee>Hello, this is stationary homepage.
    <br><br>
    Go through the left navigation menu</marquee></h3><br><br>
    <div class="col-md-55" style="height:250px;width:250px;">
      <div class="thumbnail" style="height:150px;width:200px;">
        <div class="image view view-first" style="height:150px;">

      <img src='../../media/{{data.userimg}}' height='100%' width='100%'>
        </div>
        </div>
        </div>
  <div class="profile" width="300px">
  <h2>Profile Details</h2>
  <b>Username:</b>{{data.user}}<br>
  <b>Firstname:</b>{{data.first_name}}<br>
  <b>Lastname:</b>{{data.last_name}}<br>
  <b>Email Address:</b>{{data.email}}<br>
  <b>Phone:</b>{{data.phone_number}}<br>
  </div>

</div>

{%endblock%}

Stationary/templates/Scategory_index.html
{% extends 'base1.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">

  <table class="table">
    <tr><th><h3><marquee>Category Name</marquee></h3></th></tr>
    <div class='right' style="position:relative;left:615px;">
      <a href="/Stationary/add_Scategory/"><button class="btn btn-round btn-primary">Add Category</button></a>
      <a href="/Stationary/add_Sproduct/"><button class="btn btn-round btn-primary">Add product</button></a>
      <a href="/Stationary/query/"><button class="btn btn-round btn-primary">Send query to admin</button></a>
    </div>

  {% for c1 in cat %}
  <tr>
    <td><b> {{c1.CatName}}</b></td>
    <td><img src='../../media/{{c1.CatImg}}' height='80' width='80'></td>
    <td> <a href="/Stationary/edit_Scategory/?CatId={{c1.CatId}}"><input class="btn btn-round btn-primary" type="button" value="Edit"> </a></td>
    <td> <a href="/Stationary/delete_Scategory/?CatId={{c1.CatId}}"><input class="btn btn-round btn-danger" type="button" value="Delete"> </a></td>
    <td> <a href="/Stationary/SproductbyId/?CatId={{c1.CatId}}"><input class="btn btn-round btn-primary" type="button" value="Show"> </a></td>
  </tr>

  {% endfor %}
    </table>

</div>


{% endblock %}

Stationary/templates/Sproduct_delete.html
{% extends "base1.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
<h3>Are you sure you want to delete Product
    '{{Pid.PName}}'
    ?
</h3>
<form method="POST">
  {% csrf_token %}
  <a href="/Stationary/Scategory_index"><input class="btn btn-round btn-default" type="button" value="Cancel"> </a>
  <input type="submit" value="Delete" class="btn btn-round btn-primary">
</form>
</div>

{%endblock%}

Stationary/templates/productdetail.html
{% extends "base1.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>

<div class="container">
  <center><h1>Product</h1></center>


  <center><b>Name: </b><b>{{pro.PName}}</b></center><br><center><b>Price: </b><b>{{pro.Price}}</b></center> <br><center><img src='../../../media/{{pro.PImg}}' height="200px" width="200px"></center> <br>


  <form method="POST" action="">
    <input type="hidden" value="1" name="product">
    <br>

    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

    <input type="hidden" name="Pid" value="{{pro.Pid}}" required="" id="id_Pid">

    <input type="hidden" name="Price" value="{{pro.Price}}" required="" id="id_Price"><br>
    <center>
    <label for="id_quantity">Quantity:</label><input type="number" name="quantity" required="" id="id_quantity">
    </center>
    <br>

    <center>
    <input type="submit" value="Add to CART?" class="btn btn-success">
    </center>
  </form>


  </div>
{% endblock %}

Stationary/templates/productdetail1.html
{% extends "base1.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>

<div class="container">
  <center><h1>Product</h1></center>


  <center><b>Name: </b><b>{{pro.PName}}</b></center><br><center><b>Price: </b><b>{{pro.Price}}</b></center> <br><center><img src='../../../media/{{pro.PImg}}' height="200px" width="200px"></center> <br>


  <form method="POST" action="">
    <input type="hidden" value="1" name="product">
    <br>

    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

    <input type="hidden" name="Pid" value="{{pro.Pid}}" required="" id="id_Pid">

    <input type="hidden" name="Price" value="{{pro.Price}}" required="" id="id_Price"><br>
    <center>
    <label for="id_quantity">Quantity:</label><input type="number" name="quantity" required="" id="id_quantity">
    </center>
    <br>

    <center>
    <input type="submit" value="Add to CART?" class="btn btn-success">
    </center>
  </form>


  </div>
{% endblock %}

Stationary/templates/putquery.html
{% extends "base1.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}


</div>
<div class="container">
  <form method="POST">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
      <p><label for="id_querytext">Querytext:</label> <input class="rohit" type="text" name="querytext"  maxlength="500" required="" id="id_querytext"></p>
<p> <input  type="hidden" name="isreviewed" id="id_isreviewed"></p>
      <a href="/Canteen/Ccategory_index/"><input class="btn btn-round btn-default" type="button" value="Back"> </a>
      <input type="submit" value="submit" class="btn btn-round btn-primary">
  </form>
</div>

{%endblock%}