Demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Canteen/',include('Canteen.urls')),
    path('Stationary/',include('Stationary.urls')),
    path('Stream/',include('Stream.urls')),
    path('Student/',include('Student.urls')),
    path('UserManagement/',include('UserManagement.urls')),
    path('Library/',include('Library.urls')),
    path('Librarian/',include('Librarian.urls')),
    path('users/',include('users.urls')),
    path('rht/',include('rht.urls')),
    path('myadmin/',include('myadmin.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Student/urls.py
from django.conf.urls import url,include
from . import views
from django.urls import path
from Student.views import *


urlpatterns = [
path('index_view/',index),
url(r'^logout/$',views.logout1),
path('OrderShowForC/',OrderShowForC),
path('uploaddoc/',uploaddoc),
path('updatedoc/',updatedoc),
path('DetailOfOrderForC/',DetailOfOrderForC),
path('OrderShowForS/',OrderShowForS),
path('DetailOfOrderForS/',DetailOfOrderForS),
path('OrderShowForL/',OrderShowForL),
path('DetailOfOrderForL/',DetailOfOrderForL),
path('updateprofile/',updateprofile),
path('updatesem/',updatesem),
path('blockcard/',blockcard),
]

rht/urls.py
from django.conf.urls import url,include
from . import views


urlpatterns = [
url(r'^$',views.index_view),
]

Student/models.py
from django.db import models
from users.models import Student

class Documents(models.Model):
    enroll=models.IntegerField(primary_key=True,unique=True,blank=False,default=151260107099)
    adharcard=models.FileField(upload_to="documents",blank=True,null=True)
    result10=models.FileField(upload_to="documents",blank=True,null=True)
    result12=models.FileField(upload_to="documents",blank=True,null=True)
    semresult1=models.FileField(upload_to="documents",blank=True,null=True)
    semresult2=models.FileField(upload_to="documents",blank=True,null=True)
    semresult3=models.FileField(upload_to="documents",blank=True,null=True)
    semresult4=models.FileField(upload_to="documents",blank=True,null=True)
    semresult5=models.FileField(upload_to="documents",blank=True,null=True)
    semresult6=models.FileField(upload_to="documents",blank=True,null=True)
    semresult7=models.FileField(upload_to="documents",blank=True,null=True)

Student/forms.py
from django import forms
from django.forms import ModelForm
from Student.models import Documents
from users.models import MyUser,Student

class DocForm(forms.ModelForm):

    class Meta:
        model = Documents
        fields = '__all__'

class UpdateDocForm(forms.ModelForm):
    class Meta:
        model=Documents
        exclude=('enroll',)

class MyUserForm(forms.ModelForm):
    class Meta:
        model=MyUser
        fields=('first_name','last_name','email','phone_number','userimg',)


class MyUserForm1(forms.ModelForm):
    class Meta:
        model=MyUser
        fields=('first_name','last_name','email','phone_number','userimg',)

class StudentForm1(forms.ModelForm):
    class Meta:
        model=Student
        fields=('sem',)

Student/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
import datetime
from users.views import login1
from Stationary.models import Scategory, Sproduct,StatOrder,StatOrderDetails
from Canteen.models import Ccategory, Cproduct,CatOrder,CatOrderDetails
from Librarian.models import LibraryOrder1,LibOrderDetails1
from users.models import MyUser,Student,card
from Student.models import Documents
from Student.forms import DocForm,MyUserForm1,StudentForm1,UpdateDocForm
from users.forms import MyUserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login,logout

@login_required
def logout1(request):
    logout(request)
    return login1(request)


def check_user(request):
    if 'user_role' in request.session and request.session['user_role']=="Student":
        return True
    return False


def StudentHome(request):
    if not check_user(request):
        return HttpResponse(str(request.user)+" user is not allowed to view this page")
    return render(request,'StudentHome.html')

def index(request):
    context={}
    username = request.session['username']
    context['username']=username
    s=MyUser.objects.get(user=username)
    s1=Student.objects.get(user=username)
    print(s1.enroll)
    print(s1.sem)
    print(s1.stream)
    context['data']=s
    context['data1']=s1
    return render(request,'student_home.html',context)



def OrderShowForC(request):
    context={}
    username = request.session['username']
    s1=Student.objects.get(user=username)
    print(s1.enroll)
    context['instance']=CatOrder.objects.filter(UserId=s1.enroll).order_by('-CatOrderId')
    return render(request,'OrderShowForC.html',context)

def DetailOfOrderForC(request):
    context={ }
    CatOrderId = request.GET['CatOrderId']
    print(CatOrderId)
    data=CatOrderDetails.objects.filter(CatOrderId=CatOrderId)
    context['data']=data

    mul=1
    add=0
    for i in data:
        mul=i.Price*i.quantity
        add=add+mul
    context['add']=add
    return render(request,'DetailOfOrderForC.html',context)

def OrderShowForS(request):
    context={}
    username = request.session['username']
    s1=Student.objects.get(user=username)
    print(s1.enroll)
    context['instance']=StatOrder.objects.filter(UserId=s1.enroll).order_by('-StatOrderId')
    return render(request,'OrderShowForS.html',context)

def DetailOfOrderForS(request):
    context={ }
    StatOrderId = request.GET['StatOrderId']
    print(StatOrderId)
    data=StatOrderDetails.objects.filter(StatOrderId=StatOrderId)
    context['data']=data

    mul=1
    add=0
    for i in data:
        mul=i.Price*i.quantity
        add=add+mul
    context['add']=add
    return render(request,'DetailOfOrderForS.html',context)

def OrderShowForL(request):
    context={}
    username = request.session['username']
    s1=Student.objects.get(user=username)
    print(s1.enroll)
    context['instance']=LibraryOrder1.objects.filter(UserId=s1.enroll).order_by('-LibOrderId')
    return render(request,'OrderShowForL.html',context)

def DetailOfOrderForL(request):
    context={ }
    LibOrderId = request.GET['LibOrderId']
    print(LibOrderId)
    data=LibOrderDetails1.objects.filter(LibOrderId=LibOrderId)
    s=LibraryOrder1.objects.get(LibOrderId=LibOrderId)
    context['date']=s.DateOfOrder
    context['data']=data
    return render(request,'DetailOfOrderForL.html',context)

def uploaddoc(request):
    context={}
    if request.method == 'GET':
        username = request.session['username']
        s=Student.objects.get(user=username)
        print(s.enroll)
        if Documents.objects.filter(enroll=s.enroll).exists():
            return render(request,'uploadalready.html')
        else:
            context['object']=s.enroll
            form = DocForm()
    elif request.method == "POST":
        print("here in post request")
        form = DocForm(data=request.POST,files=request.FILES)
        print("here is the data")
        if form.is_valid():
            print("form is valid")
            cat = form.save()

            return HttpResponseRedirect('/Student/index_view/')
    context['form'] = form
    return render(request, 'uploaddoc.html', context)


def updatedoc(request):
    context={}
    if request.method == 'GET':
        username = request.session['username']
        print("hello ", username)
        s1=Student.objects.get(user=username)
        print(s1.enroll)

        instance = Documents.objects.get(enroll=s1.enroll)
        form = UpdateDocForm(instance=instance)
    elif request.method == "POST":
        username = request.session['username']
        print("hello ", username)
        s1=Student.objects.get(user=username)
        print(s1.enroll)
        instance = Documents.objects.get(enroll=s1.enroll)
        form = UpdateDocForm(data=request.POST,files=request.FILES,instance=instance)
        if form.is_valid():
            cat = form.save()
            messages.success(request,"documents updated successfully")
            return HttpResponseRedirect('/Student/updatedoc/')
    context['form'] = form
    return render(request, 'updatedoc.html', context)


def updateprofile(request):
    context={}
    if request.method=='GET':
        username=request.session['username']
        s1=MyUser.objects.get(user=username)
        s2=Student.objects.get(user=username)
        context['enroll']=s2.enroll
        form=MyUserForm1(instance=s1)
    elif request.method=="POST":
        username=request.session['username']
        s1=MyUser.objects.get(user=username)
        form=MyUserForm1(data=request.POST,files=request.FILES,instance=s1)
        if form.is_valid():
            cat=form.save()
            return HttpResponseRedirect('/Student/index_view/')
    context['form']=form
    return render(request,"updateprofile.html",context)

def updatesem(request):
    context = {}
    if request.method =='GET':
        enroll=request.GET['enroll']
        s2=Student.objects.get(enroll=enroll)
        print(s2.sem)
        form1=StudentForm1()
        print(form1)
    elif request.method == "POST":
        enroll=request.GET['enroll']
        s2=Student.objects.get(enroll=enroll)

        form2 = StudentForm1(data=request.POST)
        if form2.is_valid():
            cat1=form2.save()
            return HttpResponseRedirect('/Student/index_view/')
    context['form']=form1
    return render(request,'updatesem1.html',context)

def blockcard(request):
    context={}
    if request.method=="GET":
        username=request.session['username']
        s2=Student.objects.get(user=username)
        s3=card.objects.get(enroll=s2.enroll)
        data=s3.isblocked
        context['data']=data
    elif request.method=="POST":
        username=request.session['username']
        s2=Student.objects.get(user=username)
        s=card.objects.get(enroll=s2.enroll)
        if s.isblocked==True:
            s.isblocked=False
        else:
            s.isblocked=True
        s.save()
        if s.isblocked==True:
            messages.warning(request,"card is blocked")
        else:
            messages.success(request,"card is unblocked")
        return HttpResponseRedirect('/Student/index_view/')

    return render(request,"cardblock.html",context)

Student/templates/DetailOfOrderForC.html
{% extends 'base4.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <table class="table">
    <tr><th><b>Product Name</b></th><th><b>Price</b></th><th><b>Quantity</b></th><th><b>Total<b></th>
    <tr><th></th><th></th><th></th></tr>
  {% for c1 in data %}
  <tr>
    <td><b> {{c1.Pid}}</b></td>
    <td><b> {{c1.Price}}</b></td>
    <td><b> {{c1.quantity}}</b></td>
    <td><b>{% widthratio c1.Price 1 c1.quantity %}</td></b>
  </tr>

  {% endfor %}
    </table>
    <div style="position: relative;
left: 722px;">
    <b>Total amount to be paid:</b> <b>{{add}}</b>
    </div>
<a href="/Student/OrderShowForC/"><input class="btn btn-round btn-default" type="button" value="Back"> </a>
</div>


{% endblock %}

Student/templates/DetailOfOrderForL.html
{% extends 'base4.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <table class="table">
    <tr><th><b>Date</b></th><th><b>Book Id</b></th><th><b>BookName</b></th><th><b>Serial Number</b></th><th><b>Stock Number<b></th>
    <tr><th></th><th></th><th></th></tr>
  {% for c1 in data %}
  <tr>
    <td><b> {{date}} </b></td>
    <td><b> {{c1.BookId}}</b></td>
    <td><b> {{c1.BookName}}</b></td>
    <td><b> {{c1.BookSerialNumber}}</b></td>
    <td><b>{{c1.BookStockSerial}}</td></b>
  </tr>

  {% endfor %}
    </table>

<a href="/Student/OrderShowForL/"><input class="btn btn-round btn-default" type="button" value="Back"> </a>
</div>


{% endblock %}

Student/templates/DetailOfOrderForS.html
{% extends 'base4.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <table class="table">
    <tr><th><b>Product Name</b></th><th><b>Price</b></th><th><b>Quantity</b></th><th><b>Total<b></th>
    <tr><th></th><th></th><th></th></tr>
  {% for c1 in data %}
  <tr>
    <td><b> {{c1.Pid}}</b></td>
    <td><b> {{c1.Price}}</b></td>
    <td><b> {{c1.quantity}}</b></td>
    <td><b>{% widthratio c1.Price 1 c1.quantity %}</td></b>
  </tr>

  {% endfor %}
    </table>
    <div style="position: relative;
left: 722px;">
    <b>Total amount to be paid:</b> <b>{{add}}</b>
    </div>
<a href="/Student/OrderShowForS/"><input class="btn btn-round btn-default" type="button" value="Back"> </a>
</div>


{% endblock %}

Student/templates/OrderShowForL.html
{% extends 'base4.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <form method="POST" action="">
      {% csrf_token %}


  <table class="table">

      <tr><td><b>DateTime</b></td></tr>
  {% for c1 in instance %}
  <tr>
    

    <td><b> {{c1.DateOfOrder}}</b></td>
    <td><a href="/Student/DetailOfOrderForL/?LibOrderId={{c1.LibOrderId}}"><input class="btn btn-round btn-primary" type="button" value="Detail"> </a></td>

  </tr>

  {% endfor %}
    </table>
  <div>


{% endblock %}

Student/templates/OrderShowForS.html
{% extends 'base4.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} message">
            <i class="close icon"></i>
            {{message | safe}}
        </div>
    {% endfor %}
{% endif %}




<div class="container">
  <form method="POST" action="">
      {% csrf_token %}


  <table class="table">

      <tr><td><b>DateTime</b></td></tr>
  {% for c1 in instance %}
  <tr>
    

    <td><b> {{c1.DateOfOrder}}</b></td>
    <td><a href="/Student/DetailOfOrderForS/?StatOrderId={{c1.StatOrderId}}"><input class="btn btn-round btn-primary" type="button" value="Detail"> </a></td>

  </tr>

  {% endfor %}
    </table>
  <div>


{% endblock %}

Student/templates/StudentHome.html
{% extends 'base4.html' %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
  <h3><marquee>Hello, this is Student homepage.Go through the left navigation menu</marquee></h3>
</div>

{%endblock%}

Student/templates/base4.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>| Student | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
   <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="#" class="site_title"><i class="fa fa-paw"></i> <span>SAL</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">

              <div class="profile_info">
                <span><h3>Welcome,</h3></span>
                <h3>{{username}}</h3>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">

                <ul class="nav side-menu">
                  <li><a><i class="fa fa-edit"></i> Profile <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Student/updateprofile/">Update Profile</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-tasks"></i> Order History <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Student/OrderShowForC/">Canteen Orders</a></li>
                      <li><a href="/Student/OrderShowForS/">Stationary orders</a></li>
                      <li><a href="/Student/OrderShowForL/">library Orders</a></li>

                    </ul>
                  </li>
                  <li><a><i class="fa fa-desktop"></i> Upload Docs <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Student/uploaddoc/">Upload Docs</a></li>
                      <li><a href="/Student/updatedoc/">Update Docs</a></li>

                    </ul>
                  </li>
                  <li><a><i class="fa fa-table"></i> Block Card <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Student/blockcard/">card block request</a></li>

                    </ul>
                  </li>
                  
                </ul>
              </div>
              <div class="menu_section">

              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">

            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">{{username}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">

                    <li><a href="/Student/logout/"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">

                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main" style=" background-image: linear-gradient(-65deg, #7a91a8, white);">
          <div class="">



{% block content %}

{% endblock %}

        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'build/js/custom.min.js' %}"></script>
  </body>
</html>

Student/templates/cardblock.html
{% extends "base4.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
  <div class="right" style="position:relative;left:300px;top:150px;">
<h3>Do you want to block/unblock your card?
</h3>
<form method="POST">
    {% csrf_token %}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="/Student/index_view/"><input class="btn btn-round btn-default" type="button" value="back"> </a>
    <input type="submit" value="Yes" class="btn btn-round btn-primary">
</form>
</div>
</div>

{%endblock%}

Student/templates/student_home.html
{% extends "base4.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
  <h3><marquee>Hello, this is student homepage.
    <br><br>
    Go through the left navigation menu</marquee></h3><br><br>
    <div class="col-md-55" style="height:250px;width:250px;">
      <div class="thumbnail" style="height:200px;width:200px;">
        <div class="image view view-first" style="height:200px;">

      <img src='../../media/{{data.userimg}}' height='100%' width='100%'>
        </div>
        </div>
        </div>
  <div class="profile" width="300px">
  <h2>Profile Details</h2>
  <b>Username:</b>{{data.user}}<br>
  <b>Firstname:</b>{{data.first_name}}<br>
  <b>Lastname:</b>{{data.last_name}}<br>
  <b>Enrolment:</b>{{data1.enroll}}<br>
  <b>Semester:</b>{{data1.sem}}<br>
  <b>Stream:</b>{{data1.stream}}<br>
  <b>Email Address:</b>{{data.email}}<br>
  <b>Phone:</b>{{data.phone_number}}<br>

  </div>

</div>

{%endblock%}

Student/templates/updatedoc.html
{% extends "base4.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


<form method="POST" enctype="multipart/form-data">

  {% csrf_token %}
  <table class="table">
{{form.as_table}}
<tr>
  <td><a href="/Student/index_view/"><input class="btn btn-round btn-default" type="button" value="Back"> </a></td>
  <td><input type="submit" value="Submit" class="btn btn-round btn-primary"></td>

</tr>
</table>
</form>
  </div>


{%endblock%}

Student/templates/updateprofile.html
{% extends "base4.html" %}

{% block content %}

<div class="container">
  <div class="x_content">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}
  <div class="right" style="position:relative;left:800px;">
  <a href="/Student/updatesem/?enroll={{enroll}}"><input class="btn btn-round btn-primary" type="button" value="Update Semester"> </a>
  </div>
  <form method="POST" enctype="multipart/form-data">

  {{form.as_p}}
  {% csrf_token %}

    <input type="submit" value="Update" class="btn btn-round btn-primary">

  </form>

</div>
  </div>


{%endblock%}

Student/templates/updatesem1.html
{% extends "base4.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table">
{{form.as_table}}

<tr>
  <td><a href="/Student/updateprofile/"><input class="btn btn-round btn-default" type="button" value="Back"> </a></td>
  <td><input type="submit" value="Submit" class="btn btn-round btn-primary"></td>

</tr>
</table>
</form>
  </div>


{%endblock%}

Student/templates/uploadalready.html
{% extends "base4.html" %}

{% block content %}
<div class="ui main container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} message">
                    <i class="close icon"></i>
                    {{message | safe}}
                </div>
            {% endfor %}
        {% endif %}
</div>
<div class="container">
<h3>Hello user,<br><br>
  You have already uploaded the documents once.<br><br>
  You can update from the option given below.<br><br>
    <a href="/Student/updatedoc/"><input class="btn btn-round btn-default" type="button" value="update documents"> </a>
</h3>

</div>

{%endblock%}

Student/templates/uploaddoc.html
{% extends "base4.html" %}

{% block content %}

<div class="container">
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{{message.tags}} message">
              <i class="close icon"></i>
              {{message | safe}}
          </div>
      {% endfor %}
  {% endif %}


<form method="POST" enctype="multipart/form-data">

  {% csrf_token %}
  <table class="table">
    <form method="POST" enctype="multipart/form-data">

      <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
      <table class="table">
    <tbody><tr><td><input type="hidden" name="enroll" value="{{object}}" required="" id="id_enroll">


    </td></tr>
    <tr><th><label for="id_adharcard">Adharcard:</label></th><td><input type="file" name="adharcard" id="id_adharcard"></td></tr>
    <tr><th><label for="id_result10">Result10:</label></th><td><input type="file" name="result10" id="id_result10"></td></tr>
    <tr><th><label for="id_result12">Result12:</label></th><td><input type="file" name="result12" id="id_result12"></td></tr>
    <tr><th><label for="id_semresult1">Semresult1:</label></th><td><input type="file" name="semresult1" id="id_semresult1"></td></tr>
    <tr><th><label for="id_semresult2">Semresult2:</label></th><td><input type="file" name="semresult2" id="id_semresult2"></td></tr>
    <tr><th><label for="id_semresult3">Semresult3:</label></th><td><input type="file" name="semresult3" id="id_semresult3"></td></tr>
    <tr><th><label for="id_semresult4">Semresult4:</label></th><td><input type="file" name="semresult4" id="id_semresult4"></td></tr>
    <tr><th><label for="id_semresult5">Semresult5:</label></th><td><input type="file" name="semresult5" id="id_semresult5"></td></tr>
    <tr><th><label for="id_semresult6">Semresult6:</label></th><td><input type="file" name="semresult6" id="id_semresult6"></td></tr>
    <tr><th><label for="id_semresult7">Semresult7:</label></th><td><input type="file" name="semresult7" id="id_semresult7"></td></tr>
    <tr>
      <td><a href="/Student/index_view/"><input class="btn btn-round btn-default" type="button" value="Back"> </a></td>
      <td><input type="submit" value="Submit" class="btn btn-round btn-primary"></td>

    </tr>
    </tbody></table>
    </form>
  </div>


{%endblock%}